### ISSUE TITLE
Weekly Scrum - March 3rd

### ISSUE THREAD

**Issue by DavidHaighton** [based-4806/BasedSurvey#12]
### what have I done this week? (with link(s) to the relevant GitHub Issue(s))
for everyone: 
- decided on the project to make
- developed ORM model design, implementation and tests
- setup this github

### what will I do next week? (with link(s) to the relevant GitHub Issue(s))
for everyone: 
 - everything else for the first milestone

### what is holding me back? (if applicable)
for everyone: 
- other classes lmao

**Comment by kevinhquach** [comment]
### what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Made PR for #8 
- Reviewed #22 , #25 , #36 

### what will I do next week? (with link(s) to the relevant GitHub Issue(s))
 - Learn more about htmx
 - Consider addressing #28 , #29 , #38 , #39

### what is holding me back? (if applicable)
- Spending time on 4th year project

**Comment by Shashaank5** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
#40

**Comment by DavidSciola** [comment]
**what have I done this week? (with link(s) to the relevant GitHub Issue(s))**

- Created PRs for https://github.com/based-4806/BasedSurvey/pull/22, https://github.com/based-4806/BasedSurvey/pull/35 and https://github.com/based-4806/BasedSurvey/pull/36
- Reviewed https://github.com/based-4806/BasedSurvey/pull/17, https://github.com/based-4806/BasedSurvey/pull/26 and https://github.com/based-4806/BasedSurvey/pull/41

**what will I do next week? (with link(s) to the relevant GitHub Issue(s))**

- Learn htmx
- Fix https://github.com/based-4806/BasedSurvey/issues/34
- Maybe improve fill survey page with other quality of life features
- Help out with other issues in general

**what is holding me back? (if applicable)**

- The human body requires 7 or more hours of sleep each night 🛌
