### ISSUE TITLE
ORM is inconsistent when it is running in real time versus running in a test environment. 

### ISSUE THREAD

**Issue by mack-wallace** [based-4806/BasedSurvey#30]
While testing for removing a question from the survey, it seems that the unit test does not actually remove the question. However, the unit testing for adding a question works. Furthermore, while running the Web application for real, removing questions from the survey works. Below are attached screen shots of the test environment and the real environment respectively. 

![testing](https://user-images.githubusercontent.com/72233859/223614836-53e5e7ea-d439-405e-a7a7-57b08916ca0e.png)
![real environment](https://user-images.githubusercontent.com/72233859/223614839-57f34658-0639-47a8-8419-e366dbf565ff.png)

**Comment by DavidSciola** [comment]
I was also having a similar issue when writing the unit tests for FillSurveyController. In my test I use mockMvc to perform a post request to fill out a set of responses for the survey however the question response lists are still size 0.
![image](https://user-images.githubusercontent.com/35578827/223619952-47f1061e-bd25-4ab6-b797-fed1ed476785.png)
![image](https://user-images.githubusercontent.com/35578827/223619988-8b506a48-c632-4f76-99c1-2ddc1dfc3f88.png)
