### ISSUE TITLE
Database state is persisting between test cases

### ISSUE THREAD

**Issue by DavidSciola** [based-4806/BasedSurvey#34]
The fact that Question ids are autogenerated is causing an issue in WebQuestionControllerTest where findById(1,2,3..) is used to identify questions within the question repository. This issue is caused when another test case runs beforehand and creates its own questions within the question repository and increments the id counter.

One temporary fix I found was to dynamically save the question ids in variables q1ID, q2ID, q3ID upon question creation and then use these variables within the test cases.
![image](https://user-images.githubusercontent.com/35578827/223621405-24f4be70-9aab-4432-b09a-085e6cff0d42.png)
![image](https://user-images.githubusercontent.com/35578827/223621436-033e898a-8c26-4b4b-8941-a3c479a43789.png)
![image](https://user-images.githubusercontent.com/35578827/223621483-73add91a-3fc7-4f73-9593-1f2fd5eab35d.png)

I feel like there must be some cleaner fix to this issue where we force the database to start from scratch for each test case.

**Comment by kevinhquach** [comment]
I also used this fix, though without making any static variables.
![image](https://user-images.githubusercontent.com/8755691/223628265-1bd1665e-a806-4ebb-97b8-e2427aab2590.png)
