### ISSUE TITLE
Scrum meeting 3-10

### ISSUE THREAD

**Issue by DavidHaighton** [based-4806/BasedSurvey#49]

**Comment by mack-wallace** [comment]
### what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Made PR for #75 #76 #81 
- Reviewed #71 #68 

### what will I do next week? (with link(s) to the relevant GitHub Issue(s))
 - Learn more about htmx
 - Make preparations and complete the video. 

### what is holding me back? (if applicable)
- I can only handle a certain amount of Basedness per day.

**Comment by DavidHaighton** [comment]
# What issues have I done recently?
#63 
#58 
#57 
#54 
#34 
#30 
Reviewed a few as well 
# Next week
- probably develop a cellphone addiction the way im always on call with the based department
- add postgress to azure
- general security and cleanup
- more htmx
# Whats holding me back
- (whoever these people in the photo are)[https://i.kym-cdn.com/photos/images/newsfeed/001/462/629/964.jpeg]
- the presentation video on htmx
- not knowing what to spend the rest of my azure credits on

**Comment by kevinhquach** [comment]
### what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- Made #82 for #44 #60 #61 
- Reviewed #48 #69 

### what will I do next week? (with link(s) to the relevant GitHub Issue(s))
 - Learn more about htmx
 - Make preparations and complete the video. 
 - Finish more testing

### what is holding me back? (if applicable)
- 4907

**Comment by Shashaank5** [comment]
> ### what have I done this week? (with link(s) to the relevant GitHub Issue(s))
> #56 #55 one of them still in PR for a small change but working on it right now.

> ### what will I do next week? (with link(s) to the relevant GitHub Issue(s))
> * Learn more about htmx and make more complex videos
> * Make preparations and complete the video.
> * Try to get the PR for my other issue in 

> ### what is holding me back? (if applicable)
> * 4907
> I am in india for a week and it's been difficult to make changes (will pick up more in the next milestone)

**Comment by DavidSciola** [comment]
**what have I done this week? (with link(s) to the relevant GitHub Issue(s))**
https://github.com/based-4806/BasedSurvey/pull/94
https://github.com/based-4806/BasedSurvey/pull/93
https://github.com/based-4806/BasedSurvey/pull/91

**what will I do next week? (with link(s) to the relevant GitHub Issue(s))**
Learn more about htmx and work on filling out 
Make preparations and complete the video.

**what is holding me back? (if applicable)**
4907
